-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- if/else 分支内均可 await；while 内 await 累加
-- 期望 RESULT: 35  （path A: 10+5=15, then while 加两次 delay(10) → 35）

function run_branch(flag)
  local sm = { _state = 0, _locals = {}, _await_tmp = nil, _fail_to = nil, _fail_mode = nil, _err = nil, _err_kind = nil, _propagate = false, _has_return = false, _return_val = nil }
  sm._locals.flag = flag
  function sm:step(ok, val)
    if ok ~= true then
      if self._fail_to ~= nil then
        self._err = val
        self._err_kind = (ok == "canceled") and "canceled" or "rejected"
        if self._fail_mode == "propagate" then self._propagate = true end
        self._state = self._fail_to
        self._fail_to = nil
        self._fail_mode = nil
        self._await_tmp = nil
      else
        if ok == "canceled" then return Task.canceled(val) end
        return Task.rejected(val)
      end
    else
      if self._await_tmp then
        self._locals[self._await_tmp] = val
        self._await_tmp = nil
      end
    end
    while true do
      local s = self._state
      if s == 0 then
        self._locals.total = 0
        if (self._locals.flag == 1) then
          self._state = 1
        else
          self._state = 4
        end
      elseif s == 1 then
        self._state = 2
        self._await_tmp = "_aw0"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(delay(10), self)
      elseif s == 2 then
        self._locals.a = self._locals._aw0
        self._locals.total = (self._locals.total + self._locals.a)
        self._state = 3
        self._await_tmp = "_aw1"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(delay(5), self)
      elseif s == 3 then
        self._locals.b = self._locals._aw1
        self._locals.total = (self._locals.total + self._locals.b)
        self._state = 6
      elseif s == 4 then
        self._state = 5
        self._await_tmp = "_aw2"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(delay(100), self)
      elseif s == 5 then
        self._locals.x = self._locals._aw2
        self._locals.total = (self._locals.total + self._locals.x)
        self._state = 6
      elseif s == 6 then
        self._locals.i = 0
        self._state = 7
      elseif s == 7 then
        if (self._locals.i < 2) then
          self._state = 8
        else
          self._state = 10
        end
      elseif s == 8 then
        self._state = 9
        self._await_tmp = "_aw3"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(delay(10), self)
      elseif s == 9 then
        self._locals.d = self._locals._aw3
        self._locals.total = (self._locals.total + self._locals.d)
        self._locals.i = (self._locals.i + 1)
        self._state = 7
      elseif s == 10 then
        return Task.resolved(self._locals.total)
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

