-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- cancel_scope + ambient Cancellation.current()
-- 宿主里 Cancellation.scope 压 ambient；async 内 delay 读 Cancellation.current()
-- 下一轮微任务取消 → do_work 的 Task 变为 canceled
-- 期望 RESULT: canceled

local Cancellation = require("runtime.cancellation")

function do_work()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil, _fail_to = nil, _fail_mode = nil, _err = nil, _err_kind = nil, _propagate = false, _has_return = false, _return_val = nil }
  function sm:step(ok, val)
    if ok ~= true then
      if self._fail_to ~= nil then
        self._err = val
        self._err_kind = (ok == "canceled") and "canceled" or "rejected"
        if self._fail_mode == "propagate" then self._propagate = true end
        self._state = self._fail_to
        self._fail_to = nil
        self._fail_mode = nil
        self._await_tmp = nil
      else
        if ok == "canceled" then return Task.canceled(val) end
        return Task.rejected(val)
      end
    else
      if self._await_tmp then
        self._locals[self._await_tmp] = val
        self._await_tmp = nil
      end
    end
    while true do
      local s = self._state
      if s == 0 then
        self._state = 1
        self._await_tmp = "_aw0"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(delay(10), self)
      elseif s == 1 then
        self._locals.a = self._locals._aw0
        self._state = 2
        self._await_tmp = "_aw1"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(delay(100), self)
      elseif s == 2 then
        self._locals.b = self._locals._aw1
        return Task.resolved((self._locals.a + self._locals.b))
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end


-- 普通 Lua：创建 scope、安排取消、返回 Task（可能被取消）
local function start_cancelable_work()
  return Cancellation.scope(function(cts)
    Task.defer(function()
      cts:cancel()
    end)
    return do_work()
  end)
end

function run_cancel_scope()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil, _fail_to = nil, _fail_mode = nil, _err = nil, _err_kind = nil, _propagate = false, _has_return = false, _return_val = nil }
  function sm:step(ok, val)
    if ok ~= true then
      if self._fail_to ~= nil then
        self._err = val
        self._err_kind = (ok == "canceled") and "canceled" or "rejected"
        if self._fail_mode == "propagate" then self._propagate = true end
        self._state = self._fail_to
        self._fail_to = nil
        self._fail_mode = nil
        self._await_tmp = nil
      else
        if ok == "canceled" then return Task.canceled(val) end
        return Task.rejected(val)
      end
    else
      if self._await_tmp then
        self._locals[self._await_tmp] = val
        self._await_tmp = nil
      end
    end
    while true do
      local s = self._state
      if s == 0 then
        self._locals.outcome = "ok"
        self._state = 1
        self._await_tmp = "_aw0"
        self._fail_to = 2
        self._fail_mode = "catch"
        return Task.await_then(start_cancelable_work(), self)
      elseif s == 1 then
        self._locals.v = self._locals._aw0
        self._locals.outcome = self._locals.v
        self._err = nil
        self._state = 6
      elseif s == 2 then
        self._locals.e = self._err
        if ((type(self._locals.e) == "table") and self._locals.e.canceled) then
          self._state = 3
        else
          self._state = 4
        end
      elseif s == 3 then
        self._locals.outcome = "canceled"
        self._state = 5
      elseif s == 4 then
        self._locals.outcome = "error"
        self._state = 5
      elseif s == 5 then
        self._err = nil
        self._state = 6
      elseif s == 6 then
        return Task.resolved(self._locals.outcome)
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

