-- Generated by lua-async-dialect transpiler (no coroutines)
local Task = require("runtime.task")

function add_one(x)
  local sm = { _state = 0, _locals = {} }
  sm._locals.x = x
  function sm:step(ok, val)
    if not ok then return Task.rejected(val) end
    local s = self._state
    if s == 0 then
      self._state = 1
      return Task.await_then(delay(5), self)
    elseif s == 1 then
      self._locals._aw0 = val
      self._locals.y = self._locals._aw0
      return Task.resolved((self._locals.x + self._locals.y))
    end
  end
  return sm:step(true)
end

function main()
  local sm = { _state = 0, _locals = {} }
  function sm:step(ok, val)
    if not ok then return Task.rejected(val) end
    local s = self._state
    if s == 0 then
      self._state = 1
      return Task.await_then(add_one(10), self)
    elseif s == 1 then
      self._locals._aw0 = val
      self._locals.v = self._locals._aw0
      self._state = 2
      return Task.await_then(add_one(self._locals.v), self)
    elseif s == 2 then
      self._locals._aw1 = val
      self._locals.w = self._locals._aw1
      return Task.resolved(self._locals.w)
    end
  end
  return sm:step(true)
end
