-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- 演示：async 函数互相 await（add_one 链式调用，期望 (10+5)+5=20）
function add_one(x)
  local sm = { _state = 0, _locals = {}, _await_tmp = nil }
  sm._locals.x = x
  function sm:step(ok, val)
    if not ok then return Task.rejected(val) end
    if self._await_tmp then
      self._locals[self._await_tmp] = val
      self._await_tmp = nil
    end
    while true do
      local s = self._state
      if s == 0 then
        self._state = 1
        self._await_tmp = "_aw0"
        return Task.await_then(delay(5), self)
      elseif s == 1 then
        self._locals.y = self._locals._aw0
        return Task.resolved((self._locals.x + self._locals.y))
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end


function main()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil }
  function sm:step(ok, val)
    if not ok then return Task.rejected(val) end
    if self._await_tmp then
      self._locals[self._await_tmp] = val
      self._await_tmp = nil
    end
    while true do
      local s = self._state
      if s == 0 then
        self._state = 1
        self._await_tmp = "_aw0"
        return Task.await_then(add_one(10), self)
      elseif s == 1 then
        self._locals.v = self._locals._aw0
        self._state = 2
        self._await_tmp = "_aw1"
        return Task.await_then(add_one(self._locals.v), self)
      elseif s == 2 then
        self._locals.w = self._locals._aw1
        return Task.resolved(self._locals.w)
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

