-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- Task.delay + 虚拟时钟：不睡真实时间，由 run_demo 的 Task.advance 推进
-- 期望 RESULT: 30  （10+20）

function run_delay_timer()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil, _fail_to = nil, _fail_mode = nil, _err = nil, _err_kind = nil, _propagate = false, _has_return = false, _return_val = nil }
  function sm:step(ok, val)
    if ok ~= true then
      if self._fail_to ~= nil then
        self._err = val
        self._err_kind = (ok == "canceled") and "canceled" or "rejected"
        if self._fail_mode == "propagate" then self._propagate = true end
        self._state = self._fail_to
        self._fail_to = nil
        self._fail_mode = nil
        self._await_tmp = nil
      else
        if ok == "canceled" then return Task.canceled(val) end
        return Task.rejected(val)
      end
    else
      if self._await_tmp then
        self._locals[self._await_tmp] = val
        self._await_tmp = nil
      end
    end
    while true do
      local s = self._state
      if s == 0 then
        self._state = 1
        self._await_tmp = "_aw0"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(Task.delay(10), self)
      elseif s == 1 then
        self._locals.a = self._locals._aw0
        self._state = 2
        self._await_tmp = "_aw1"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(Task.delay(20), self)
      elseif s == 2 then
        self._locals.b = self._locals._aw1
        return Task.resolved((self._locals.a + self._locals.b))
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

