-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- Task.forget：火忘式吞掉拒绝，避免未处理 rejection
-- 同时验证 from_exception / from_canceled 别名
-- 期望 RESULT: ok

local saw_unhandled = false

local function setup()
  saw_unhandled = false
  Task.set_unhandled_rejection(function(_reason, _task)
    saw_unhandled = true
  end)
end

function run_forget()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil, _fail_to = nil, _fail_mode = nil, _err = nil, _err_kind = nil, _propagate = false, _has_return = false, _return_val = nil }
  function sm:step(ok, val)
    if ok ~= true then
      if self._fail_to ~= nil then
        self._err = val
        self._err_kind = (ok == "canceled") and "canceled" or "rejected"
        if self._fail_mode == "propagate" then self._propagate = true end
        self._state = self._fail_to
        self._fail_to = nil
        self._fail_mode = nil
        self._await_tmp = nil
      else
        if ok == "canceled" then return Task.canceled(val) end
        return Task.rejected(val)
      end
    else
      if self._await_tmp then
        self._locals[self._await_tmp] = val
        self._await_tmp = nil
      end
    end
    while true do
      local s = self._state
      if s == 0 then
        setup()
        self._locals.bad = Task.from_exception("should-not-surface")
        self._locals.bad:forget()
        self._locals.canceled = Task.from_canceled()
        Task.forget(self._locals.canceled)
        self._state = 1
        self._await_tmp = "_aw0"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(Task.delay(1), self)
      elseif s == 1 then
        self._locals._ = self._locals._aw0
        if saw_unhandled then
          self._state = 2
        else
          self._state = 4
        end
      elseif s == 2 then
        return Task.resolved("leaked")
      elseif s == 3 then
        self._state = 5
      elseif s == 4 then
        self._state = 5
      elseif s == 5 then
        return Task.resolved("ok")
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

