-- Generated by lua-async-dialect transpiler (no coroutines)
local Task = require("runtime.task")

function hello()
  local sm = { _state = 0, _locals = {} }
  function sm:step(ok, val)
    if not ok then return Task.rejected(val) end
    local s = self._state
    if s == 0 then
      self._state = 1
      return Task.await_then(delay(10), self)
    elseif s == 1 then
      self._locals._aw0 = val
      self._locals.a = self._locals._aw0
      self._state = 2
      return Task.await_then(delay(20), self)
    elseif s == 2 then
      self._locals._aw1 = val
      self._locals.b = self._locals._aw1
      return Task.resolved((self._locals.a + self._locals.b))
    end
  end
  return sm:step(true)
end
