-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- 演示：连续两次 await delay，再把结果相加返回（期望 10+20=30）
function hello()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil }
  function sm:step(ok, val)
    if not ok then return Task.rejected(val) end
    if self._await_tmp then
      self._locals[self._await_tmp] = val
      self._await_tmp = nil
    end
    while true do
      local s = self._state
      if s == 0 then
        self._state = 1
        self._await_tmp = "_aw0"
        return Task.await_then(delay(10), self)
      elseif s == 1 then
        self._locals.a = self._locals._aw0
        self._state = 2
        self._await_tmp = "_aw1"
        return Task.await_then(delay(20), self)
      elseif s == 2 then
        self._locals.b = self._locals._aw1
        return Task.resolved((self._locals.a + self._locals.b))
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

