-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- 嵌入式方言：普通 Lua 宿主 + 一个 async 函数
-- 期望 RESULT: 42  （helpers 与表字段参与计算）

local Config = {
  base = 10,
  label = "mixed",
}

local function double(x)
  return x * 2
end

local function add_base(x)
  return x + Config.base
end

function run_mixed()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil }
  function sm:step(ok, val)
    if not ok then return Task.rejected(val) end
    if self._await_tmp then
      self._locals[self._await_tmp] = val
      self._await_tmp = nil
    end
    while true do
      local s = self._state
      if s == 0 then
        self._state = 1
        self._await_tmp = "_aw0"
        return Task.await_then(delay(7), self)
      elseif s == 1 then
        self._locals.a = self._locals._aw0
        self._locals.b = double(self._locals.a)
        self._state = 2
        self._await_tmp = "_aw1"
        return Task.await_then(delay(5), self)
      elseif s == 2 then
        self._locals.c = self._locals._aw1
        self._locals.sum = add_base((self._locals.b + self._locals.c))
        self._locals.msg = (Config.label .. (":" .. self._locals.sum))
        self._state = 3
        self._await_tmp = "_aw2"
        return Task.await_then(delay(13), self)
      elseif s == 3 then
        self._locals.extra = self._locals._aw2
        return Task.resolved((self._locals.sum + self._locals.extra))
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

