-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- 异步流水线：fetch 桩返回 Task.resolved，中间用普通 Lua 变换，再 await 链
-- Task 由 splice 转译器在输出顶部注入；此处直接使用。
-- 期望 RESULT: 110

local function fetch_user(id)
  return Task.resolved({ id = id, score = 40 })
end

local function fetch_bonus(user)
  return Task.resolved(user.score + 10)
end

local function transform(n)
  return n * 2
end

function run_pipeline()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil }
  function sm:step(ok, val)
    if not ok then return Task.rejected(val) end
    if self._await_tmp then
      self._locals[self._await_tmp] = val
      self._await_tmp = nil
    end
    while true do
      local s = self._state
      if s == 0 then
        self._state = 1
        self._await_tmp = "_aw0"
        return Task.await_then(fetch_user(1), self)
      elseif s == 1 then
        self._locals.user = self._locals._aw0
        self._state = 2
        self._await_tmp = "_aw1"
        return Task.await_then(fetch_bonus(self._locals.user), self)
      elseif s == 2 then
        self._locals.bonus = self._locals._aw1
        self._locals.scaled = transform(self._locals.bonus)
        self._state = 3
        self._await_tmp = "_aw2"
        return Task.await_then(delay(10), self)
      elseif s == 3 then
        self._locals.tip = self._locals._aw2
        return Task.resolved((self._locals.scaled + self._locals.tip))
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

