-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- try/catch/finally：await 失败进入 catch，finally 必跑
-- 期望 RESULT: caught-fin

local finally_mark = ""

local function boom()
  return Task.rejected("boom")
end

function run_try_catch()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil, _fail_to = nil, _fail_mode = nil, _err = nil, _err_kind = nil, _propagate = false, _has_return = false, _return_val = nil }
  function sm:step(ok, val)
    if ok ~= true then
      if self._fail_to ~= nil then
        self._err = val
        self._err_kind = (ok == "canceled") and "canceled" or "rejected"
        if self._fail_mode == "propagate" then self._propagate = true end
        self._state = self._fail_to
        self._fail_to = nil
        self._fail_mode = nil
        self._await_tmp = nil
      else
        if ok == "canceled" then return Task.canceled(val) end
        return Task.rejected(val)
      end
    else
      if self._await_tmp then
        self._locals[self._await_tmp] = val
        self._await_tmp = nil
      end
    end
    while true do
      local s = self._state
      if s == 0 then
        self._locals.result = "ok"
        self._state = 1
        self._await_tmp = "_aw0"
        self._fail_to = 2
        self._fail_mode = "catch"
        return Task.await_then(boom(), self)
      elseif s == 1 then
        self._locals.x = self._locals._aw0
        self._locals.result = self._locals.x
        self._propagate = false
        self._state = 3
      elseif s == 2 then
        self._locals.e = self._err
        self._locals.result = "caught"
        self._propagate = false
        self._state = 3
      elseif s == 3 then
        self._locals.finally_mark = "fin"
        if self._has_return then
          local rv = self._return_val
          self._has_return = false
          self._return_val = nil
          self._err = nil
          return Task.resolved(rv)
        elseif self._propagate then
          local ek = self._err_kind
          local ev = self._err
          self._propagate = false
          self._err = nil
          if ek == "canceled" then return Task.canceled(ev) end
          return Task.rejected(ev)
        else
          self._err = nil
          self._state = 4
        end
      elseif s == 4 then
        return Task.resolved((self._locals.result .. ("-" .. self._locals.finally_mark)))
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

