-- Generated by lua-async-dialect splice transpiler (no coroutines)
local Task = require("runtime.task")
-- Task.when_all：并行等待多个 delay，汇总结果
-- 期望 RESULT: 60  （10+20+30）

function run_when_all()
  local sm = { _state = 0, _locals = {}, _await_tmp = nil, _fail_to = nil, _fail_mode = nil, _err = nil, _err_kind = nil, _propagate = false, _has_return = false, _return_val = nil }
  function sm:step(ok, val)
    if ok ~= true then
      if self._fail_to ~= nil then
        self._err = val
        self._err_kind = (ok == "canceled") and "canceled" or "rejected"
        if self._fail_mode == "propagate" then self._propagate = true end
        self._state = self._fail_to
        self._fail_to = nil
        self._fail_mode = nil
        self._await_tmp = nil
      else
        if ok == "canceled" then return Task.canceled(val) end
        return Task.rejected(val)
      end
    else
      if self._await_tmp then
        self._locals[self._await_tmp] = val
        self._await_tmp = nil
      end
    end
    while true do
      local s = self._state
      if s == 0 then
        self._state = 1
        self._await_tmp = "_aw0"
        self._fail_to = nil
        self._fail_mode = nil
        return Task.await_then(Task.when_all({delay(10), delay(20), delay(30)}), self)
      elseif s == 1 then
        self._locals.results = self._locals._aw0
        self._locals.sum = 0
        self._locals.i = 1
        self._state = 2
      elseif s == 2 then
        if (self._locals.i <= (#self._locals.results)) then
          self._state = 3
        else
          self._state = 4
        end
      elseif s == 3 then
        self._locals.sum = (self._locals.sum + self._locals.results[self._locals.i])
        self._locals.i = (self._locals.i + 1)
        self._state = 2
      elseif s == 4 then
        return Task.resolved(self._locals.sum)
      else
        return Task.rejected("bad state " .. tostring(s))
      end
    end
  end
  return sm:step(true)
end

